# Generated by Django 4.1.7 on 2023-02-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email is required', 'invalid': 'Please Enter a Valid Email Address', 'required': 'Email is required', 'unique': 'A user with that email already exists.'}, help_text='Required. Add a valid email address', max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
